#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# It also distribute requests using a roundrobin algorithm

sudo apt update

if ! dpkg -l | grep -q "haproxy"; then
	sudo apt install haproxy -y
fi

echo "ENABLED=1" | sudo tee /etc/default/haproxy >/dev/null

printf "
frontend omarkh.tech
	bind		*:80

	default_backend web_servers

backend web_servers
	balance roundrobin
	server	334551-web-01 54.235.193.23:80 check
	server	334551-web-02 54.209.125.126:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null

sudo service haproxy restart
