#!/usr/bin/env bash
# fix a bug preventing connecting to port 80
apt-get update
apt-get install nginx -y
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
